---
title: Contact Us 
---

Please follow the links below to contact us on any of these topics:


## Participate in Glider Rodeo
Do you have a PAM system, Glider, or analysis method you’d like to test as part of this effort? *We cannot currently offer funding to participate, but may be able to provide logistic support- lab space for preparation, vessels for glider deployment and/or recoveries, if associated with our efforts.*

If you are interested in participating in the Glider Rodeo, please fill out the [Glider Rodeo Participation Form](https://forms.gle/pbHmbKHBMFVvRXto9){target="_blank"}.


## Suggestion for Glider Rodeo Metrics/Analyses
In addition to comparing general system and sampling specifications, we have planned to assess a diverse set of survey, data quality, and acoustic detection metrics across each system. Do you have suggestions for metrics that would help evaluate PAM-equipped glider options?

If you have suggestions on metrics/analyses to consider for the Glider Rodeo, please fill out the [Glider Rodeo Metrics form](https://forms.gle/gMRRGH2vrGxFwtvK6){target="_blank"}


## New Technology
Glider and PAM technology, as well as software and analytical methods to work with these technologies, are rapidly advancing and we have an interest in learning about developing or new technologies as they evolve. Are you involved with a new technology?

If you are developing a new technology that you would like to share with our community of scientists, please complete the [New Technology Form](https://forms.gle/m3dYdzWwrgggjGyg7){target="_blank"}


## PAM-Glider data from other regions
Although we are focusing our field efforts on two regions, we are interested in collaborating to include data from other systems and areas if you have data you are willing to share.

If you have PAM-glider data that you feel would be useful analyzing with our Glider Rodeo Data, please complete the [Alternative Data Form](https://forms.gle/fqaw896PjEsvx4Eh9){target="_blank"}


