---
title: Metrics 
---

During the glider rodeo, we will identify and define a series of metrics to be calculated for each platform. These metrics will provide a means of comparison to identify strengths and limitations, as well as ranges of performance. The metrics include:

1.  **Operational metrics:** Measures related to active operations and routine functioning of the platform and systems (including glider platform, oceanographic sensors, battery/power, satellite transmissions, software interface, and glider piloting).

2.  **Passive acoustic metrics:** Measure related to assessing detection, classification, and localization of animals.

3.  **Soundscape Metrics:** Measures related to assessing ambient sound, including acoustic sensitivity/calibration, self-noise, available data, and ability to measure soundscape in hybrid millidecade. There is a natural crossover between soundscape and bioacoustics measures; soundscape metrics will be all PAM metrics not directly associated with animal sounds.

4.  **Resource metrics:** measures of resources (personnel, expertise, equipment, materials, time, budget) needed to implement the technology.

We are actively working with experts to develop a suite of metrics that provide a means of assessing each platform that can be completed with the available resources. We will make these metrics (including their definition) publicly accessible here when they are available.
